### ISSUE TITLE
Featurization

### ISSUE THREAD

**Issue by kaueltzen** [ncfrey/magnetic-topological-materials#4]
Hi @ncfrey @mkhorton 

I am interested in ML of magnetic ground states and wanted to reproduce some of the features you used in your work “High-throughput search for magnetic and topological order in transition metal oxides”.
However, I find some feature descriptions unclear, for example what algorithm was used to obtain the coordination environment or how exactly the next-nearest neighbor TM-TM distance function was implemented.
Is it possible for you to provide the script used for feature generation?

Thanks and best regards,
Katharina

**Comment by ncfrey** [comment]
Hi @kaueltzen, all structural features (including coordination envs, distances, etc.) can be computed with Pymatgen: https://github.com/materialsproject/pymatgen

**Comment by kaueltzen** [comment]
Thank you for your answer @ncfrey.
I am aware that you can compute these structural features with pymatgen. Nevertheless, I find some of your feature descriptions ambiguous, for example, if the multiplicity of sites was included or not in the averaging of (next) nearest neighbor TM distances or what algorithm (for example CrystalNN, EconNN,...) was used to obtain the mean coordination number (since the results may differ significantly depending on the method).
This is why I was asking for your scripts used for feature generation.

**Comment by mkhorton** [comment]
Hi @kaueltzen, thanks for your interest. I didn't perform the featurization myself so cannot answer specifics, but some of them (structural complexity per atom, sine coulomb matrix, etc.) I believe were generated with [matminer](https://hackingmaterials.lbl.gov/matminer/) (which in turn uses pymatgen). Matminer provides automatic featurization for a number of structural features, I don't imagine the default arguments for these featurizers were changed. Matminer also generates features via [Magpie](https://bitbucket.org/wolverton/magpie/src/master/) too.

**Comment by kaueltzen** [comment]
Thank you @mkhorton and sorry @ncfrey: I did not notice until now that your nn and nnn specific features are implemented in the HeisenbergMapper because I did not expect them to be in a class to compute exchange parameters from low energy magnetic orderings. This answers all my feature-related questions. Thanks again!
